# The access key and secret key should be retrieved from the AWS account that accesses the SQS queue
# These values should be base64 encoded: echo -n <key> | base64

apiVersion: v1
kind: Secret
metadata: 
  name: aws-secret
  namespace: argo-events
type: Opaque
data: 
  accesskey: <base64 encoded access key>
  secretkey: <base64 encoded secret key>
