apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: nos-sqs
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: nos-dep
      eventSourceName: nos-sqs
      eventName: newofs
  triggers:
    - template:
        name: nos-sqs-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: nos-sqs-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # this is the value that should be overridden
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: nos-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value